### ISSUE TITLE
is this configurable?

### ISSUE THREAD

**Issue by laurencefass** [shuding/next-view-transitions#25]
IF the answer is no to any/all of these questions do you think they would be cool features for a more extensive animation library?

Disclaimer: I havent tried it yet so no idea how it works just responding to the README.,

Can/could I configure a default transition at the root level?

Can /could I configure transitions per route e.g. on the `<Link>?`

Can/could I configure transitions per Component?

**Comment by edwardshturman** [comment]
Hey Laurence,

I've been able to set a default transition at the root level using vanilla CSS. Here's an example tweaked based on [one from MDN](https://github.com/mdn/dom-examples/blob/main/view-transitions/mpa/styles.css):

```css
@keyframes move-out {
  from {
    transform: translateY(0%);
  }

  to {
    transform: translateY(-100%);
  }
}

@keyframes move-in {
  from {
    transform: translateY(100%);
  }

  to {
    transform: translateY(0%);
  }
}

::view-transition-old(root) {
  animation: 1s ease both move-out;
}

::view-transition-new(root) {
  animation: 1s ease both move-in;
}
```

I would imagine you could override as needed by writing CSS with greater selector specificity.

From what I gather, `next-view-transitions` is a wrapper for compatibility with the Next.js App Router and the `<Link>` component, rather than a Next-specific implementation of View Transitions. Could be wrong / Shu and team could have plans for that, so don't quote me on it :)


Hope this helps,

Edward
